import express from "express"
import dotenv from "dotenv"
import cors from "cors"
import morgan from "morgan"
import { connectDB } from "./config/database"
import authRoutes from "./routes/auth"
import customerRoutes from "./routes/customer"
import invoiceRoutes from "./routes/invoice"
import quoteRoutes from "./routes/quote"
import errorHandler from "./middleware/errorHandler"